# Generated by Django 5.0.6 on 2024-12-18 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_systemuser_is_student_systemuser_is_teacher'),
        ('models_manager', '0003_delete_authuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='models_manager.account', verbose_name='Аккаунт'),
        ),
    ]
