# Generated by Django 5.0.6 on 2024-12-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel('Groups', 'StudentGroups')
    ]
