# Generated by Django 5.0.6 on 2024-12-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models_manager', '0002_studentgroups_delete_authuser_delete_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
